deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl unzip bash
    - curl -LO https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    - unzip -o terraform_1.5.7_linux_amd64.zip -d /tmp/terraform_bin
    - mv /tmp/terraform_bin/terraform /usr/local/bin/
    - terraform version
  script:
    - cd terraform
    # Export AWS credentials for terraform
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - terraform init
    - terraform apply -auto-approve
  only:
    - main

